/* IS_AUTOGENERATED_SO_ALLOW_AUTODELETE=YES */
/* The previous line is to allow auto deletion */

#import "TapTelegraphSvcGen.h"

@implementation PlayerInfo

@synthesize golgiIdIsSet;
- (NSString *)getGolgiId
{
    return golgiId;
}
- (void)setGolgiId:(NSString *)_golgiId
{
    golgiId = _golgiId;
    golgiIdIsSet = (_golgiId != nil) ? YES : NO;
}
@synthesize nameIsSet;
- (NSString *)getName
{
    return name;
}
- (void)setName:(NSString *)_name
{
    name = _name;
    nameIsSet = (_name != nil) ? YES : NO;
}
@synthesize hiScoreIsSet;
- (NSInteger)getHiScore
{
    return hiScore;
}
- (void)setHiScore:(NSInteger )_hiScore
{
    hiScore = _hiScore;
    hiScoreIsSet = YES;
}
@synthesize gameIdIsSet;
- (NSString *)getGameId
{
    return gameId;
}
- (void)setGameId:(NSString *)_gameId
{
    gameId = _gameId;
    gameIdIsSet = (_gameId != nil) ? YES : NO;
}
@synthesize gameSeedIsSet;
- (NSInteger)getGameSeed
{
    return gameSeed;
}
- (void)setGameSeed:(NSInteger )_gameSeed
{
    gameSeed = _gameSeed;
    gameSeedIsSet = YES;
}
@synthesize appVerIsSet;
- (NSInteger)getAppVer
{
    return appVer;
}
- (void)setAppVer:(NSInteger )_appVer
{
    appVer = _appVer;
    appVerIsSet = YES;
}
@synthesize osIsSet;
- (NSString *)getOs
{
    return os;
}
- (void)setOs:(NSString *)_os
{
    os = _os;
    osIsSet = (_os != nil) ? YES : NO;
}

+ (PlayerInfo *)deserialiseFromString: (NSString *)string
{
    return [PlayerInfo deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}

+ (PlayerInfo *)deserialiseFromPayload: (GolgiPayload *)payload
{
    PlayerInfo *inst = [[PlayerInfo alloc] initWithIsSet:NO];
    BOOL corrupt = NO;

    {
        NSString *str;
        if((str = [payload getStringWithTag:@"1:"]) != nil){
            inst.golgiId = str;
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSString *str;
        if((str = [payload getStringWithTag:@"2:"]) != nil){
            inst.name = str;
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"3:"]) != nil){
            inst.hiScore = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSString *str;
        if((str = [payload getStringWithTag:@"4:"]) != nil){
            inst.gameId = str;
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"5:"]) != nil){
            inst.gameSeed = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"6:"]) != nil){
            inst.appVer = [num intValue];
        }
    }

    {
        NSString *str;
        if((str = [payload getStringWithTag:@"7:"]) != nil){
            inst.os = str;
        }
    }

    return (corrupt) ? nil : inst;
}

- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}

- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];

    if(golgiIdIsSet){
        [str appendFormat:@"%@1: \"%@\"\n", prefix, [CSL  NTLEscapeString:golgiId]];
    }
    if(nameIsSet){
        [str appendFormat:@"%@2: \"%@\"\n", prefix, [CSL  NTLEscapeString:name]];
    }
    if(hiScoreIsSet){
        [str appendFormat:@"%@3: %ld\n", prefix, (long)hiScore];
    }
    if(gameIdIsSet){
        [str appendFormat:@"%@4: \"%@\"\n", prefix, [CSL  NTLEscapeString:gameId]];
    }
    if(gameSeedIsSet){
        [str appendFormat:@"%@5: %ld\n", prefix, (long)gameSeed];
    }
    if(appVerIsSet){
        [str appendFormat:@"%@6: %ld\n", prefix, (long)appVer];
    }
    if(osIsSet){
        [str appendFormat:@"%@7: \"%@\"\n", prefix, [CSL  NTLEscapeString:os]];
    }

    return [NSString stringWithString:str];
}

- (PlayerInfo *)init
{
    return [self initWithIsSet:YES];
}

- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        golgiId = @"";
        golgiIdIsSet = defIsSet;
        name = @"";
        nameIsSet = defIsSet;
        hiScoreIsSet = defIsSet;
        gameId = @"";
        gameIdIsSet = defIsSet;
        gameSeedIsSet = defIsSet;
        os = @"";
    }

    return self;

}

@end
@implementation TapData

@synthesize gameIdIsSet;
- (NSString *)getGameId
{
    return gameId;
}
- (void)setGameId:(NSString *)_gameId
{
    gameId = _gameId;
    gameIdIsSet = (_gameId != nil) ? YES : NO;
}
@synthesize screenOffsetIsSet;
- (NSInteger)getScreenOffset
{
    return screenOffset;
}
- (void)setScreenOffset:(NSInteger )_screenOffset
{
    screenOffset = _screenOffset;
    screenOffsetIsSet = YES;
}
@synthesize playerYIsSet;
- (NSInteger)getPlayerY
{
    return playerY;
}
- (void)setPlayerY:(NSInteger )_playerY
{
    playerY = _playerY;
    playerYIsSet = YES;
}
@synthesize deltaYIsSet;
- (NSInteger)getDeltaY
{
    return deltaY;
}
- (void)setDeltaY:(NSInteger )_deltaY
{
    deltaY = _deltaY;
    deltaYIsSet = YES;
}
@synthesize indexIsSet;
- (NSInteger)getIndex
{
    return index;
}
- (void)setIndex:(NSInteger )_index
{
    index = _index;
    indexIsSet = YES;
}
@synthesize scoreIsSet;
- (NSInteger)getScore
{
    return score;
}
- (void)setScore:(NSInteger )_score
{
    score = _score;
    scoreIsSet = YES;
}

+ (TapData *)deserialiseFromString: (NSString *)string
{
    return [TapData deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}

+ (TapData *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapData *inst = [[TapData alloc] initWithIsSet:NO];
    BOOL corrupt = NO;

    {
        NSString *str;
        if((str = [payload getStringWithTag:@"1:"]) != nil){
            inst.gameId = str;
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"2:"]) != nil){
            inst.screenOffset = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"3:"]) != nil){
            inst.playerY = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"4:"]) != nil){
            inst.deltaY = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"5:"]) != nil){
            inst.index = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"6:"]) != nil){
            inst.score = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    return (corrupt) ? nil : inst;
}

- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}

- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];

    if(gameIdIsSet){
        [str appendFormat:@"%@1: \"%@\"\n", prefix, [CSL  NTLEscapeString:gameId]];
    }
    if(screenOffsetIsSet){
        [str appendFormat:@"%@2: %ld\n", prefix, (long)screenOffset];
    }
    if(playerYIsSet){
        [str appendFormat:@"%@3: %ld\n", prefix, (long)playerY];
    }
    if(deltaYIsSet){
        [str appendFormat:@"%@4: %ld\n", prefix, (long)deltaY];
    }
    if(indexIsSet){
        [str appendFormat:@"%@5: %ld\n", prefix, (long)index];
    }
    if(scoreIsSet){
        [str appendFormat:@"%@6: %ld\n", prefix, (long)score];
    }

    return [NSString stringWithString:str];
}

- (TapData *)init
{
    return [self initWithIsSet:YES];
}

- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        gameId = @"";
        gameIdIsSet = defIsSet;
        screenOffsetIsSet = defIsSet;
        playerYIsSet = defIsSet;
        deltaYIsSet = defIsSet;
        indexIsSet = defIsSet;
        scoreIsSet = defIsSet;
    }

    return self;

}

@end
@implementation GameOverData

@synthesize gameIdIsSet;
- (NSString *)getGameId
{
    return gameId;
}
- (void)setGameId:(NSString *)_gameId
{
    gameId = _gameId;
    gameIdIsSet = (_gameId != nil) ? YES : NO;
}
@synthesize screenOffsetIsSet;
- (NSInteger)getScreenOffset
{
    return screenOffset;
}
- (void)setScreenOffset:(NSInteger )_screenOffset
{
    screenOffset = _screenOffset;
    screenOffsetIsSet = YES;
}
@synthesize playerYIsSet;
- (NSInteger)getPlayerY
{
    return playerY;
}
- (void)setPlayerY:(NSInteger )_playerY
{
    playerY = _playerY;
    playerYIsSet = YES;
}
@synthesize scoreIsSet;
- (NSInteger)getScore
{
    return score;
}
- (void)setScore:(NSInteger )_score
{
    score = _score;
    scoreIsSet = YES;
}

+ (GameOverData *)deserialiseFromString: (NSString *)string
{
    return [GameOverData deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}

+ (GameOverData *)deserialiseFromPayload: (GolgiPayload *)payload
{
    GameOverData *inst = [[GameOverData alloc] initWithIsSet:NO];
    BOOL corrupt = NO;

    {
        NSString *str;
        if((str = [payload getStringWithTag:@"1:"]) != nil){
            inst.gameId = str;
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"2:"]) != nil){
            inst.screenOffset = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"3:"]) != nil){
            inst.playerY = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"4:"]) != nil){
            inst.score = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    return (corrupt) ? nil : inst;
}

- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}

- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];

    if(gameIdIsSet){
        [str appendFormat:@"%@1: \"%@\"\n", prefix, [CSL  NTLEscapeString:gameId]];
    }
    if(screenOffsetIsSet){
        [str appendFormat:@"%@2: %ld\n", prefix, (long)screenOffset];
    }
    if(playerYIsSet){
        [str appendFormat:@"%@3: %ld\n", prefix, (long)playerY];
    }
    if(scoreIsSet){
        [str appendFormat:@"%@4: %ld\n", prefix, (long)score];
    }

    return [NSString stringWithString:str];
}

- (GameOverData *)init
{
    return [self initWithIsSet:YES];
}

- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        gameId = @"";
        gameIdIsSet = defIsSet;
        screenOffsetIsSet = defIsSet;
        playerYIsSet = defIsSet;
        scoreIsSet = defIsSet;
    }

    return self;

}

@end
@implementation HiScoreData

@synthesize nameIsSet;
- (NSString *)getName
{
    return name;
}
- (void)setName:(NSString *)_name
{
    name = _name;
    nameIsSet = (_name != nil) ? YES : NO;
}
@synthesize scoreIsSet;
- (NSInteger)getScore
{
    return score;
}
- (void)setScore:(NSInteger )_score
{
    score = _score;
    scoreIsSet = YES;
}

+ (HiScoreData *)deserialiseFromString: (NSString *)string
{
    return [HiScoreData deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}

+ (HiScoreData *)deserialiseFromPayload: (GolgiPayload *)payload
{
    HiScoreData *inst = [[HiScoreData alloc] initWithIsSet:NO];
    BOOL corrupt = NO;

    {
        NSString *str;
        if((str = [payload getStringWithTag:@"1:"]) != nil){
            inst.name = str;
        }
        else{
            corrupt = YES;
        }
    }

    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"2:"]) != nil){
            inst.score = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }

    return (corrupt) ? nil : inst;
}

- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}

- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];

    if(nameIsSet){
        [str appendFormat:@"%@1: \"%@\"\n", prefix, [CSL  NTLEscapeString:name]];
    }
    if(scoreIsSet){
        [str appendFormat:@"%@2: %ld\n", prefix, (long)score];
    }

    return [NSString stringWithString:str];
}

- (HiScoreData *)init
{
    return [self initWithIsSet:YES];
}

- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        name = @"";
        nameIsSet = defIsSet;
        scoreIsSet = defIsSet;
    }

    return self;

}

@end
@implementation TapTelegraph_startGame_reqArg
@synthesize playerInfoIsSet;
- (PlayerInfo *)getPlayerInfo
{
    return playerInfo;
}
- (void)setPlayerInfo:(PlayerInfo *)_playerInfo
{
    playerInfo = _playerInfo;
    playerInfoIsSet = (_playerInfo != nil) ? YES : NO;
}
+ (TapTelegraph_startGame_reqArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_startGame_reqArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_startGame_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_startGame_reqArg *inst = [[TapTelegraph_startGame_reqArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"1"]) != nil){
            [inst setPlayerInfo:[PlayerInfo deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setPlayerInfo:nil];
        }
    }
    if([inst getPlayerInfo] == nil){
        corrupt = YES;
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(playerInfoIsSet){
        [str appendString:[playerInfo serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "1"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_startGame_reqArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        playerInfo = [[PlayerInfo alloc] initWithIsSet:defIsSet];
        playerInfoIsSet = defIsSet;
    }
    return self;
}
@end
@implementation TapTelegraph_startGame_rspArg
@synthesize internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_
{
    return internalSuccess_;
}
- (void)setInternalSuccess_:(NSInteger )_internalSuccess_
{
    internalSuccess_ = _internalSuccess_;
    internalSuccess_IsSet = YES;
}
@synthesize golgiExceptionIsSet;
- (GolgiException *)getGolgiException
{
    return golgiException;
}
- (void)setGolgiException:(GolgiException *)_golgiException
{
    golgiException = _golgiException;
    golgiExceptionIsSet = (_golgiException != nil) ? YES : NO;
}
+ (TapTelegraph_startGame_rspArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_startGame_rspArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_startGame_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_startGame_rspArg *inst = [[TapTelegraph_startGame_rspArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"1:"]) != nil){
            inst.internalSuccess_ = [num intValue];
        }
    }
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"3"]) != nil){
            [inst setGolgiException:[GolgiException deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setGolgiException:nil];
        }
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(internalSuccess_IsSet){
        [str appendFormat:@"%@1: %ld\n", prefix, (long)internalSuccess_];
    }
    if(golgiExceptionIsSet){
        [str appendString:[golgiException serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "3"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_startGame_rspArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        golgiException = [[GolgiException alloc] initWithIsSet:defIsSet];
    }
    return self;
}
@end
@implementation TapTelegraph_sendTap_reqArg
@synthesize tapDataIsSet;
- (TapData *)getTapData
{
    return tapData;
}
- (void)setTapData:(TapData *)_tapData
{
    tapData = _tapData;
    tapDataIsSet = (_tapData != nil) ? YES : NO;
}
+ (TapTelegraph_sendTap_reqArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_sendTap_reqArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_sendTap_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_sendTap_reqArg *inst = [[TapTelegraph_sendTap_reqArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"1"]) != nil){
            [inst setTapData:[TapData deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setTapData:nil];
        }
    }
    if([inst getTapData] == nil){
        corrupt = YES;
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(tapDataIsSet){
        [str appendString:[tapData serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "1"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_sendTap_reqArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        tapData = [[TapData alloc] initWithIsSet:defIsSet];
        tapDataIsSet = defIsSet;
    }
    return self;
}
@end
@implementation TapTelegraph_sendTap_rspArg
@synthesize internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_
{
    return internalSuccess_;
}
- (void)setInternalSuccess_:(NSInteger )_internalSuccess_
{
    internalSuccess_ = _internalSuccess_;
    internalSuccess_IsSet = YES;
}
@synthesize golgiExceptionIsSet;
- (GolgiException *)getGolgiException
{
    return golgiException;
}
- (void)setGolgiException:(GolgiException *)_golgiException
{
    golgiException = _golgiException;
    golgiExceptionIsSet = (_golgiException != nil) ? YES : NO;
}
+ (TapTelegraph_sendTap_rspArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_sendTap_rspArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_sendTap_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_sendTap_rspArg *inst = [[TapTelegraph_sendTap_rspArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"1:"]) != nil){
            inst.internalSuccess_ = [num intValue];
        }
    }
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"3"]) != nil){
            [inst setGolgiException:[GolgiException deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setGolgiException:nil];
        }
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(internalSuccess_IsSet){
        [str appendFormat:@"%@1: %ld\n", prefix, (long)internalSuccess_];
    }
    if(golgiExceptionIsSet){
        [str appendString:[golgiException serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "3"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_sendTap_rspArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        golgiException = [[GolgiException alloc] initWithIsSet:defIsSet];
    }
    return self;
}
@end
@implementation TapTelegraph_gameOver_reqArg
@synthesize gameOverDataIsSet;
- (GameOverData *)getGameOverData
{
    return gameOverData;
}
- (void)setGameOverData:(GameOverData *)_gameOverData
{
    gameOverData = _gameOverData;
    gameOverDataIsSet = (_gameOverData != nil) ? YES : NO;
}
+ (TapTelegraph_gameOver_reqArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_gameOver_reqArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_gameOver_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_gameOver_reqArg *inst = [[TapTelegraph_gameOver_reqArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"1"]) != nil){
            [inst setGameOverData:[GameOverData deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setGameOverData:nil];
        }
    }
    if([inst getGameOverData] == nil){
        corrupt = YES;
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(gameOverDataIsSet){
        [str appendString:[gameOverData serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "1"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_gameOver_reqArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        gameOverData = [[GameOverData alloc] initWithIsSet:defIsSet];
        gameOverDataIsSet = defIsSet;
    }
    return self;
}
@end
@implementation TapTelegraph_gameOver_rspArg
@synthesize internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_
{
    return internalSuccess_;
}
- (void)setInternalSuccess_:(NSInteger )_internalSuccess_
{
    internalSuccess_ = _internalSuccess_;
    internalSuccess_IsSet = YES;
}
@synthesize golgiExceptionIsSet;
- (GolgiException *)getGolgiException
{
    return golgiException;
}
- (void)setGolgiException:(GolgiException *)_golgiException
{
    golgiException = _golgiException;
    golgiExceptionIsSet = (_golgiException != nil) ? YES : NO;
}
+ (TapTelegraph_gameOver_rspArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_gameOver_rspArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_gameOver_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_gameOver_rspArg *inst = [[TapTelegraph_gameOver_rspArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"1:"]) != nil){
            inst.internalSuccess_ = [num intValue];
        }
    }
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"3"]) != nil){
            [inst setGolgiException:[GolgiException deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setGolgiException:nil];
        }
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(internalSuccess_IsSet){
        [str appendFormat:@"%@1: %ld\n", prefix, (long)internalSuccess_];
    }
    if(golgiExceptionIsSet){
        [str appendString:[golgiException serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "3"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_gameOver_rspArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        golgiException = [[GolgiException alloc] initWithIsSet:defIsSet];
    }
    return self;
}
@end
@implementation TapTelegraph_streamGame_reqArg
@synthesize golgiIdIsSet;
- (NSString *)getGolgiId
{
    return golgiId;
}
- (void)setGolgiId:(NSString *)_golgiId
{
    golgiId = _golgiId;
    golgiIdIsSet = (_golgiId != nil) ? YES : NO;
}
+ (TapTelegraph_streamGame_reqArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_streamGame_reqArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_streamGame_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_streamGame_reqArg *inst = [[TapTelegraph_streamGame_reqArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        NSString *str;
        if((str = [payload getStringWithTag:@"1:"]) != nil){
            inst.golgiId = str;
        }
        else{
            corrupt = YES;
        }
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(golgiIdIsSet){
        [str appendFormat:@"%@1: \"%@\"\n", prefix, [CSL  NTLEscapeString:golgiId]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_streamGame_reqArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        golgiId = @"";
        golgiIdIsSet = defIsSet;
    }
    return self;
}
@end
@implementation TapTelegraph_streamGame_rspArg
@synthesize internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_
{
    return internalSuccess_;
}
- (void)setInternalSuccess_:(NSInteger )_internalSuccess_
{
    internalSuccess_ = _internalSuccess_;
    internalSuccess_IsSet = YES;
}
@synthesize golgiExceptionIsSet;
- (GolgiException *)getGolgiException
{
    return golgiException;
}
- (void)setGolgiException:(GolgiException *)_golgiException
{
    golgiException = _golgiException;
    golgiExceptionIsSet = (_golgiException != nil) ? YES : NO;
}
+ (TapTelegraph_streamGame_rspArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_streamGame_rspArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_streamGame_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_streamGame_rspArg *inst = [[TapTelegraph_streamGame_rspArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"1:"]) != nil){
            inst.internalSuccess_ = [num intValue];
        }
    }
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"3"]) != nil){
            [inst setGolgiException:[GolgiException deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setGolgiException:nil];
        }
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(internalSuccess_IsSet){
        [str appendFormat:@"%@1: %ld\n", prefix, (long)internalSuccess_];
    }
    if(golgiExceptionIsSet){
        [str appendString:[golgiException serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "3"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_streamGame_rspArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        golgiException = [[GolgiException alloc] initWithIsSet:defIsSet];
    }
    return self;
}
@end
@implementation TapTelegraph_getHiScore_reqArg
@synthesize pookyIsSet;
- (NSInteger)getPooky
{
    return pooky;
}
- (void)setPooky:(NSInteger )_pooky
{
    pooky = _pooky;
    pookyIsSet = YES;
}
+ (TapTelegraph_getHiScore_reqArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_getHiScore_reqArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_getHiScore_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_getHiScore_reqArg *inst = [[TapTelegraph_getHiScore_reqArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"1:"]) != nil){
            inst.pooky = [num intValue];
        }
        else{
            corrupt = YES;
        }
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(pookyIsSet){
        [str appendFormat:@"%@1: %ld\n", prefix, (long)pooky];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_getHiScore_reqArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        pookyIsSet = defIsSet;
    }
    return self;
}
@end
@implementation TapTelegraph_getHiScore_rspArg
@synthesize internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_
{
    return internalSuccess_;
}
- (void)setInternalSuccess_:(NSInteger )_internalSuccess_
{
    internalSuccess_ = _internalSuccess_;
    internalSuccess_IsSet = YES;
}
@synthesize resultIsSet;
- (HiScoreData *)getResult
{
    return result;
}
- (void)setResult:(HiScoreData *)_result
{
    result = _result;
    resultIsSet = (_result != nil) ? YES : NO;
}
@synthesize golgiExceptionIsSet;
- (GolgiException *)getGolgiException
{
    return golgiException;
}
- (void)setGolgiException:(GolgiException *)_golgiException
{
    golgiException = _golgiException;
    golgiExceptionIsSet = (_golgiException != nil) ? YES : NO;
}
+ (TapTelegraph_getHiScore_rspArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_getHiScore_rspArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_getHiScore_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_getHiScore_rspArg *inst = [[TapTelegraph_getHiScore_rspArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"1:"]) != nil){
            inst.internalSuccess_ = [num intValue];
        }
    }
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"2"]) != nil){
            [inst setResult:[HiScoreData deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setResult:nil];
        }
    }
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"3"]) != nil){
            [inst setGolgiException:[GolgiException deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setGolgiException:nil];
        }
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(internalSuccess_IsSet){
        [str appendFormat:@"%@1: %ld\n", prefix, (long)internalSuccess_];
    }
    if(resultIsSet){
        [str appendString:[result serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "2"]]];
    }
    if(golgiExceptionIsSet){
        [str appendString:[golgiException serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "3"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_getHiScore_rspArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        result = [[HiScoreData alloc] initWithIsSet:defIsSet];
        golgiException = [[GolgiException alloc] initWithIsSet:defIsSet];
    }
    return self;
}
@end
@implementation TapTelegraph_newHiScore_reqArg
@synthesize hiScoreDataIsSet;
- (HiScoreData *)getHiScoreData
{
    return hiScoreData;
}
- (void)setHiScoreData:(HiScoreData *)_hiScoreData
{
    hiScoreData = _hiScoreData;
    hiScoreDataIsSet = (_hiScoreData != nil) ? YES : NO;
}
+ (TapTelegraph_newHiScore_reqArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_newHiScore_reqArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_newHiScore_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_newHiScore_reqArg *inst = [[TapTelegraph_newHiScore_reqArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"1"]) != nil){
            [inst setHiScoreData:[HiScoreData deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setHiScoreData:nil];
        }
    }
    if([inst getHiScoreData] == nil){
        corrupt = YES;
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(hiScoreDataIsSet){
        [str appendString:[hiScoreData serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "1"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_newHiScore_reqArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        hiScoreData = [[HiScoreData alloc] initWithIsSet:defIsSet];
        hiScoreDataIsSet = defIsSet;
    }
    return self;
}
@end
@implementation TapTelegraph_newHiScore_rspArg
@synthesize internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_
{
    return internalSuccess_;
}
- (void)setInternalSuccess_:(NSInteger )_internalSuccess_
{
    internalSuccess_ = _internalSuccess_;
    internalSuccess_IsSet = YES;
}
@synthesize golgiExceptionIsSet;
- (GolgiException *)getGolgiException
{
    return golgiException;
}
- (void)setGolgiException:(GolgiException *)_golgiException
{
    golgiException = _golgiException;
    golgiExceptionIsSet = (_golgiException != nil) ? YES : NO;
}
+ (TapTelegraph_newHiScore_rspArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_newHiScore_rspArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_newHiScore_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_newHiScore_rspArg *inst = [[TapTelegraph_newHiScore_rspArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"1:"]) != nil){
            inst.internalSuccess_ = [num intValue];
        }
    }
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"3"]) != nil){
            [inst setGolgiException:[GolgiException deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setGolgiException:nil];
        }
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(internalSuccess_IsSet){
        [str appendFormat:@"%@1: %ld\n", prefix, (long)internalSuccess_];
    }
    if(golgiExceptionIsSet){
        [str appendString:[golgiException serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "3"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_newHiScore_rspArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        golgiException = [[GolgiException alloc] initWithIsSet:defIsSet];
    }
    return self;
}
@end
@implementation TapTelegraph_newPB_reqArg
@synthesize hiScoreDataIsSet;
- (HiScoreData *)getHiScoreData
{
    return hiScoreData;
}
- (void)setHiScoreData:(HiScoreData *)_hiScoreData
{
    hiScoreData = _hiScoreData;
    hiScoreDataIsSet = (_hiScoreData != nil) ? YES : NO;
}
+ (TapTelegraph_newPB_reqArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_newPB_reqArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_newPB_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_newPB_reqArg *inst = [[TapTelegraph_newPB_reqArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"1"]) != nil){
            [inst setHiScoreData:[HiScoreData deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setHiScoreData:nil];
        }
    }
    if([inst getHiScoreData] == nil){
        corrupt = YES;
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(hiScoreDataIsSet){
        [str appendString:[hiScoreData serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "1"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_newPB_reqArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        hiScoreData = [[HiScoreData alloc] initWithIsSet:defIsSet];
        hiScoreDataIsSet = defIsSet;
    }
    return self;
}
@end
@implementation TapTelegraph_newPB_rspArg
@synthesize internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_
{
    return internalSuccess_;
}
- (void)setInternalSuccess_:(NSInteger )_internalSuccess_
{
    internalSuccess_ = _internalSuccess_;
    internalSuccess_IsSet = YES;
}
@synthesize golgiExceptionIsSet;
- (GolgiException *)getGolgiException
{
    return golgiException;
}
- (void)setGolgiException:(GolgiException *)_golgiException
{
    golgiException = _golgiException;
    golgiExceptionIsSet = (_golgiException != nil) ? YES : NO;
}
+ (TapTelegraph_newPB_rspArg *)deserialiseFromString: (NSString *)string
{
    return [TapTelegraph_newPB_rspArg deserialiseFromPayload:[GolgiPayload payloadWithString:string]];
}
+ (TapTelegraph_newPB_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload
{
    TapTelegraph_newPB_rspArg *inst = [[TapTelegraph_newPB_rspArg alloc] initWithIsSet:NO];
    BOOL corrupt = NO;
    {
        NSNumber *num;
        if((num = [payload getIntWithTag:@"1:"]) != nil){
            inst.internalSuccess_ = [num intValue];
        }
    }
    {
        GolgiPayload *nestedPayload;
        if((nestedPayload = [payload getNestedWithTag:@"3"]) != nil){
            [inst setGolgiException:[GolgiException deserialiseFromPayload:nestedPayload]];
        }
        else{
            [inst setGolgiException:nil];
        }
    }
    return (corrupt) ? nil : inst;
}
- (NSString *)serialise
{
    return [self serialiseWithPrefix:@""];
}
- (NSString *)serialiseWithPrefix:(NSString *)prefix
{
    NSMutableString *str = [[NSMutableString alloc] init];
    if(internalSuccess_IsSet){
        [str appendFormat:@"%@1: %ld\n", prefix, (long)internalSuccess_];
    }
    if(golgiExceptionIsSet){
        [str appendString:[golgiException serialiseWithPrefix:[NSString stringWithFormat:@"%@%s.", prefix, "3"]]];
    }
    return [NSString stringWithString:str];
}
- (TapTelegraph_newPB_rspArg *)init
{
    return [self initWithIsSet:YES];
}
- (id)initWithIsSet:(BOOL)defIsSet
{
    if((self = [super init]) != nil){
        golgiException = [[GolgiException alloc] initWithIsSet:defIsSet];
    }
    return self;
}
@end

@interface StartGameInternalResultSender : NSObject <TapTelegraphStartGameResultSender>
{
    NSString *sender;
    NSString *msgId;
    TapTelegraph_startGame_rspArg *rsp;
}
- (StartGameInternalResultSender *) initWithSender:(NSString *)sender andMessageId:(NSString *)msgId;
@end
@implementation StartGameInternalResultSender
- (StartGameInternalResultSender *) initWithSender:(NSString *)_sender andMessageId:(NSString *)_msgId
{
    self = [self init];
    sender = _sender;
    msgId = _msgId;
    rsp = [[TapTelegraph_startGame_rspArg alloc] initWithIsSet:NO];

    return self;
}

- (void)sendResponse
{
    [Golgi sendResponsePayload:[rsp serialise] to:sender forMethod:@"startGame.TapTelegraph" withMessageId:msgId];
}

- (void)failureWithGolgiException:(GolgiException *)golgiException
{
    [rsp setGolgiException:golgiException];
    [self sendResponse];
}

- (void)success
{
    [rsp setInternalSuccess_:1];
    [self sendResponse];
}

@end

@interface StartGameInternalRequestHandler : NSObject <GolgiInternalInboundRequestHandler>
{
    id<TapTelegraphStartGameRequestReceiver> receiver;
}

- (StartGameInternalRequestHandler *)initWithReceiver:(id<TapTelegraphStartGameRequestReceiver>)receiver;
@end

@implementation StartGameInternalRequestHandler

- (void)incomingMsg:(NSString *)payload from:(NSString *)sender withMessageId:(NSString *)msgId
{
    TapTelegraph_startGame_reqArg *req = [TapTelegraph_startGame_reqArg deserialiseFromString:payload];

    if(req == nil){
        [Golgi sendRemoteError:@"Garbled Payload at Remote End" to:sender forMethod:@"startGame.TapTelegraph" withMessageId:msgId];
    }
    else{
        // Process req here
        StartGameInternalResultSender *resultSender;
        resultSender = [StartGameInternalResultSender alloc];
        resultSender = [resultSender initWithSender:sender andMessageId:msgId];
        [receiver startGameWithResultSender:resultSender andPlayerInfo:[req getPlayerInfo]];
    }
}

- (StartGameInternalRequestHandler *)initWithReceiver:(id<TapTelegraphStartGameRequestReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;

    return self;
}
@end

@interface StartGameInternalResponseHandler : NSObject <GolgiInternalInboundResponseHandler>
{
    id<TapTelegraphStartGameResultReceiver> receiver;
}

- (StartGameInternalResponseHandler *)initWithReceiver:(id<TapTelegraphStartGameResultReceiver>)receiver;
@end
@implementation StartGameInternalResponseHandler

- (void)processResponsePayload:(NSString *)payload
{
    TapTelegraph_startGame_rspArg *rsp = [TapTelegraph_startGame_rspArg deserialiseFromString:payload];

    if(rsp == nil){
        GolgiException *golgiException = [[GolgiException alloc]init];

        [golgiException setErrText:@"Corrupt Response"];
        [golgiException setErrType:GOLGI_ERRTYPE_PAYLOAD_MISMATCH];
        [receiver failureWithGolgiException:golgiException];
    }
    else if(rsp.internalSuccess_IsSet && ([rsp getInternalSuccess_] != 0)){
        [receiver success];
    }
    else if(rsp.golgiExceptionIsSet){
        [receiver failureWithGolgiException:[rsp getGolgiException]];
    }
    else{
        NSLog(@"WARNING: result for 'startGame' in Golgi Service 'TapTelegraph' has no expected response fields set!");
    }

}

- (void)processGolgiException:(GolgiException *)golgiException
{
	[receiver failureWithGolgiException:golgiException];
}

- (StartGameInternalResponseHandler *)initWithReceiver:(id<TapTelegraphStartGameResultReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;
    return self;
}

@end


@interface SendTapInternalResultSender : NSObject <TapTelegraphSendTapResultSender>
{
    NSString *sender;
    NSString *msgId;
    TapTelegraph_sendTap_rspArg *rsp;
}
- (SendTapInternalResultSender *) initWithSender:(NSString *)sender andMessageId:(NSString *)msgId;
@end
@implementation SendTapInternalResultSender
- (SendTapInternalResultSender *) initWithSender:(NSString *)_sender andMessageId:(NSString *)_msgId
{
    self = [self init];
    sender = _sender;
    msgId = _msgId;
    rsp = [[TapTelegraph_sendTap_rspArg alloc] initWithIsSet:NO];

    return self;
}

- (void)sendResponse
{
    [Golgi sendResponsePayload:[rsp serialise] to:sender forMethod:@"sendTap.TapTelegraph" withMessageId:msgId];
}

- (void)failureWithGolgiException:(GolgiException *)golgiException
{
    [rsp setGolgiException:golgiException];
    [self sendResponse];
}

- (void)success
{
    [rsp setInternalSuccess_:1];
    [self sendResponse];
}

@end

@interface SendTapInternalRequestHandler : NSObject <GolgiInternalInboundRequestHandler>
{
    id<TapTelegraphSendTapRequestReceiver> receiver;
}

- (SendTapInternalRequestHandler *)initWithReceiver:(id<TapTelegraphSendTapRequestReceiver>)receiver;
@end

@implementation SendTapInternalRequestHandler

- (void)incomingMsg:(NSString *)payload from:(NSString *)sender withMessageId:(NSString *)msgId
{
    TapTelegraph_sendTap_reqArg *req = [TapTelegraph_sendTap_reqArg deserialiseFromString:payload];

    if(req == nil){
        [Golgi sendRemoteError:@"Garbled Payload at Remote End" to:sender forMethod:@"sendTap.TapTelegraph" withMessageId:msgId];
    }
    else{
        // Process req here
        SendTapInternalResultSender *resultSender;
        resultSender = [SendTapInternalResultSender alloc];
        resultSender = [resultSender initWithSender:sender andMessageId:msgId];
        [receiver sendTapWithResultSender:resultSender andTapData:[req getTapData]];
    }
}

- (SendTapInternalRequestHandler *)initWithReceiver:(id<TapTelegraphSendTapRequestReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;

    return self;
}
@end

@interface SendTapInternalResponseHandler : NSObject <GolgiInternalInboundResponseHandler>
{
    id<TapTelegraphSendTapResultReceiver> receiver;
}

- (SendTapInternalResponseHandler *)initWithReceiver:(id<TapTelegraphSendTapResultReceiver>)receiver;
@end
@implementation SendTapInternalResponseHandler

- (void)processResponsePayload:(NSString *)payload
{
    TapTelegraph_sendTap_rspArg *rsp = [TapTelegraph_sendTap_rspArg deserialiseFromString:payload];

    if(rsp == nil){
        GolgiException *golgiException = [[GolgiException alloc]init];

        [golgiException setErrText:@"Corrupt Response"];
        [golgiException setErrType:GOLGI_ERRTYPE_PAYLOAD_MISMATCH];
        [receiver failureWithGolgiException:golgiException];
    }
    else if(rsp.internalSuccess_IsSet && ([rsp getInternalSuccess_] != 0)){
        [receiver success];
    }
    else if(rsp.golgiExceptionIsSet){
        [receiver failureWithGolgiException:[rsp getGolgiException]];
    }
    else{
        NSLog(@"WARNING: result for 'sendTap' in Golgi Service 'TapTelegraph' has no expected response fields set!");
    }

}

- (void)processGolgiException:(GolgiException *)golgiException
{
	[receiver failureWithGolgiException:golgiException];
}

- (SendTapInternalResponseHandler *)initWithReceiver:(id<TapTelegraphSendTapResultReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;
    return self;
}

@end


@interface GameOverInternalResultSender : NSObject <TapTelegraphGameOverResultSender>
{
    NSString *sender;
    NSString *msgId;
    TapTelegraph_gameOver_rspArg *rsp;
}
- (GameOverInternalResultSender *) initWithSender:(NSString *)sender andMessageId:(NSString *)msgId;
@end
@implementation GameOverInternalResultSender
- (GameOverInternalResultSender *) initWithSender:(NSString *)_sender andMessageId:(NSString *)_msgId
{
    self = [self init];
    sender = _sender;
    msgId = _msgId;
    rsp = [[TapTelegraph_gameOver_rspArg alloc] initWithIsSet:NO];

    return self;
}

- (void)sendResponse
{
    [Golgi sendResponsePayload:[rsp serialise] to:sender forMethod:@"gameOver.TapTelegraph" withMessageId:msgId];
}

- (void)failureWithGolgiException:(GolgiException *)golgiException
{
    [rsp setGolgiException:golgiException];
    [self sendResponse];
}

- (void)success
{
    [rsp setInternalSuccess_:1];
    [self sendResponse];
}

@end

@interface GameOverInternalRequestHandler : NSObject <GolgiInternalInboundRequestHandler>
{
    id<TapTelegraphGameOverRequestReceiver> receiver;
}

- (GameOverInternalRequestHandler *)initWithReceiver:(id<TapTelegraphGameOverRequestReceiver>)receiver;
@end

@implementation GameOverInternalRequestHandler

- (void)incomingMsg:(NSString *)payload from:(NSString *)sender withMessageId:(NSString *)msgId
{
    TapTelegraph_gameOver_reqArg *req = [TapTelegraph_gameOver_reqArg deserialiseFromString:payload];

    if(req == nil){
        [Golgi sendRemoteError:@"Garbled Payload at Remote End" to:sender forMethod:@"gameOver.TapTelegraph" withMessageId:msgId];
    }
    else{
        // Process req here
        GameOverInternalResultSender *resultSender;
        resultSender = [GameOverInternalResultSender alloc];
        resultSender = [resultSender initWithSender:sender andMessageId:msgId];
        [receiver gameOverWithResultSender:resultSender andGameOverData:[req getGameOverData]];
    }
}

- (GameOverInternalRequestHandler *)initWithReceiver:(id<TapTelegraphGameOverRequestReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;

    return self;
}
@end

@interface GameOverInternalResponseHandler : NSObject <GolgiInternalInboundResponseHandler>
{
    id<TapTelegraphGameOverResultReceiver> receiver;
}

- (GameOverInternalResponseHandler *)initWithReceiver:(id<TapTelegraphGameOverResultReceiver>)receiver;
@end
@implementation GameOverInternalResponseHandler

- (void)processResponsePayload:(NSString *)payload
{
    TapTelegraph_gameOver_rspArg *rsp = [TapTelegraph_gameOver_rspArg deserialiseFromString:payload];

    if(rsp == nil){
        GolgiException *golgiException = [[GolgiException alloc]init];

        [golgiException setErrText:@"Corrupt Response"];
        [golgiException setErrType:GOLGI_ERRTYPE_PAYLOAD_MISMATCH];
        [receiver failureWithGolgiException:golgiException];
    }
    else if(rsp.internalSuccess_IsSet && ([rsp getInternalSuccess_] != 0)){
        [receiver success];
    }
    else if(rsp.golgiExceptionIsSet){
        [receiver failureWithGolgiException:[rsp getGolgiException]];
    }
    else{
        NSLog(@"WARNING: result for 'gameOver' in Golgi Service 'TapTelegraph' has no expected response fields set!");
    }

}

- (void)processGolgiException:(GolgiException *)golgiException
{
	[receiver failureWithGolgiException:golgiException];
}

- (GameOverInternalResponseHandler *)initWithReceiver:(id<TapTelegraphGameOverResultReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;
    return self;
}

@end


@interface StreamGameInternalResultSender : NSObject <TapTelegraphStreamGameResultSender>
{
    NSString *sender;
    NSString *msgId;
    TapTelegraph_streamGame_rspArg *rsp;
}
- (StreamGameInternalResultSender *) initWithSender:(NSString *)sender andMessageId:(NSString *)msgId;
@end
@implementation StreamGameInternalResultSender
- (StreamGameInternalResultSender *) initWithSender:(NSString *)_sender andMessageId:(NSString *)_msgId
{
    self = [self init];
    sender = _sender;
    msgId = _msgId;
    rsp = [[TapTelegraph_streamGame_rspArg alloc] initWithIsSet:NO];

    return self;
}

- (void)sendResponse
{
    [Golgi sendResponsePayload:[rsp serialise] to:sender forMethod:@"streamGame.TapTelegraph" withMessageId:msgId];
}

- (void)failureWithGolgiException:(GolgiException *)golgiException
{
    [rsp setGolgiException:golgiException];
    [self sendResponse];
}

- (void)success
{
    [rsp setInternalSuccess_:1];
    [self sendResponse];
}

@end

@interface StreamGameInternalRequestHandler : NSObject <GolgiInternalInboundRequestHandler>
{
    id<TapTelegraphStreamGameRequestReceiver> receiver;
}

- (StreamGameInternalRequestHandler *)initWithReceiver:(id<TapTelegraphStreamGameRequestReceiver>)receiver;
@end

@implementation StreamGameInternalRequestHandler

- (void)incomingMsg:(NSString *)payload from:(NSString *)sender withMessageId:(NSString *)msgId
{
    TapTelegraph_streamGame_reqArg *req = [TapTelegraph_streamGame_reqArg deserialiseFromString:payload];

    if(req == nil){
        [Golgi sendRemoteError:@"Garbled Payload at Remote End" to:sender forMethod:@"streamGame.TapTelegraph" withMessageId:msgId];
    }
    else{
        // Process req here
        StreamGameInternalResultSender *resultSender;
        resultSender = [StreamGameInternalResultSender alloc];
        resultSender = [resultSender initWithSender:sender andMessageId:msgId];
        [receiver streamGameWithResultSender:resultSender andGolgiId:[req getGolgiId]];
    }
}

- (StreamGameInternalRequestHandler *)initWithReceiver:(id<TapTelegraphStreamGameRequestReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;

    return self;
}
@end

@interface StreamGameInternalResponseHandler : NSObject <GolgiInternalInboundResponseHandler>
{
    id<TapTelegraphStreamGameResultReceiver> receiver;
}

- (StreamGameInternalResponseHandler *)initWithReceiver:(id<TapTelegraphStreamGameResultReceiver>)receiver;
@end
@implementation StreamGameInternalResponseHandler

- (void)processResponsePayload:(NSString *)payload
{
    TapTelegraph_streamGame_rspArg *rsp = [TapTelegraph_streamGame_rspArg deserialiseFromString:payload];

    if(rsp == nil){
        GolgiException *golgiException = [[GolgiException alloc]init];

        [golgiException setErrText:@"Corrupt Response"];
        [golgiException setErrType:GOLGI_ERRTYPE_PAYLOAD_MISMATCH];
        [receiver failureWithGolgiException:golgiException];
    }
    else if(rsp.internalSuccess_IsSet && ([rsp getInternalSuccess_] != 0)){
        [receiver success];
    }
    else if(rsp.golgiExceptionIsSet){
        [receiver failureWithGolgiException:[rsp getGolgiException]];
    }
    else{
        NSLog(@"WARNING: result for 'streamGame' in Golgi Service 'TapTelegraph' has no expected response fields set!");
    }

}

- (void)processGolgiException:(GolgiException *)golgiException
{
	[receiver failureWithGolgiException:golgiException];
}

- (StreamGameInternalResponseHandler *)initWithReceiver:(id<TapTelegraphStreamGameResultReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;
    return self;
}

@end


@interface GetHiScoreInternalResultSender : NSObject <TapTelegraphGetHiScoreResultSender>
{
    NSString *sender;
    NSString *msgId;
    TapTelegraph_getHiScore_rspArg *rsp;
}
- (GetHiScoreInternalResultSender *) initWithSender:(NSString *)sender andMessageId:(NSString *)msgId;
@end
@implementation GetHiScoreInternalResultSender
- (GetHiScoreInternalResultSender *) initWithSender:(NSString *)_sender andMessageId:(NSString *)_msgId
{
    self = [self init];
    sender = _sender;
    msgId = _msgId;
    rsp = [[TapTelegraph_getHiScore_rspArg alloc] initWithIsSet:NO];

    return self;
}

- (void)sendResponse
{
    [Golgi sendResponsePayload:[rsp serialise] to:sender forMethod:@"getHiScore.TapTelegraph" withMessageId:msgId];
}

- (void)successWithResult:(HiScoreData *)result
{
    [rsp setInternalSuccess_:1];
    [rsp setResult: result];
    [self sendResponse];
}

- (void)failureWithGolgiException:(GolgiException *)golgiException
{
    [rsp setGolgiException:golgiException];
    [self sendResponse];
}

@end

@interface GetHiScoreInternalRequestHandler : NSObject <GolgiInternalInboundRequestHandler>
{
    id<TapTelegraphGetHiScoreRequestReceiver> receiver;
}

- (GetHiScoreInternalRequestHandler *)initWithReceiver:(id<TapTelegraphGetHiScoreRequestReceiver>)receiver;
@end

@implementation GetHiScoreInternalRequestHandler

- (void)incomingMsg:(NSString *)payload from:(NSString *)sender withMessageId:(NSString *)msgId
{
    TapTelegraph_getHiScore_reqArg *req = [TapTelegraph_getHiScore_reqArg deserialiseFromString:payload];

    if(req == nil){
        [Golgi sendRemoteError:@"Garbled Payload at Remote End" to:sender forMethod:@"getHiScore.TapTelegraph" withMessageId:msgId];
    }
    else{
        // Process req here
        GetHiScoreInternalResultSender *resultSender;
        resultSender = [GetHiScoreInternalResultSender alloc];
        resultSender = [resultSender initWithSender:sender andMessageId:msgId];
        [receiver getHiScoreWithResultSender:resultSender andPooky:[req getPooky]];
    }
}

- (GetHiScoreInternalRequestHandler *)initWithReceiver:(id<TapTelegraphGetHiScoreRequestReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;

    return self;
}
@end

@interface GetHiScoreInternalResponseHandler : NSObject <GolgiInternalInboundResponseHandler>
{
    id<TapTelegraphGetHiScoreResultReceiver> receiver;
}

- (GetHiScoreInternalResponseHandler *)initWithReceiver:(id<TapTelegraphGetHiScoreResultReceiver>)receiver;
@end
@implementation GetHiScoreInternalResponseHandler

- (void)processResponsePayload:(NSString *)payload
{
    TapTelegraph_getHiScore_rspArg *rsp = [TapTelegraph_getHiScore_rspArg deserialiseFromString:payload];

    if(rsp == nil){
        GolgiException *golgiException = [[GolgiException alloc]init];

        [golgiException setErrText:@"Corrupt Response"];
        [golgiException setErrType:GOLGI_ERRTYPE_PAYLOAD_MISMATCH];
        [receiver failureWithGolgiException:golgiException];
    }
    else if(rsp.internalSuccess_IsSet && ([rsp getInternalSuccess_] != 0)){
        [receiver successWithResult:[rsp getResult]];
    }
    else if(rsp.golgiExceptionIsSet){
        [receiver failureWithGolgiException:[rsp getGolgiException]];
    }
    else{
        NSLog(@"WARNING: result for 'getHiScore' in Golgi Service 'TapTelegraph' has no expected response fields set!");
    }

}

- (void)processGolgiException:(GolgiException *)golgiException
{
	[receiver failureWithGolgiException:golgiException];
}

- (GetHiScoreInternalResponseHandler *)initWithReceiver:(id<TapTelegraphGetHiScoreResultReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;
    return self;
}

@end


@interface NewHiScoreInternalResultSender : NSObject <TapTelegraphNewHiScoreResultSender>
{
    NSString *sender;
    NSString *msgId;
    TapTelegraph_newHiScore_rspArg *rsp;
}
- (NewHiScoreInternalResultSender *) initWithSender:(NSString *)sender andMessageId:(NSString *)msgId;
@end
@implementation NewHiScoreInternalResultSender
- (NewHiScoreInternalResultSender *) initWithSender:(NSString *)_sender andMessageId:(NSString *)_msgId
{
    self = [self init];
    sender = _sender;
    msgId = _msgId;
    rsp = [[TapTelegraph_newHiScore_rspArg alloc] initWithIsSet:NO];

    return self;
}

- (void)sendResponse
{
    [Golgi sendResponsePayload:[rsp serialise] to:sender forMethod:@"newHiScore.TapTelegraph" withMessageId:msgId];
}

- (void)failureWithGolgiException:(GolgiException *)golgiException
{
    [rsp setGolgiException:golgiException];
    [self sendResponse];
}

- (void)success
{
    [rsp setInternalSuccess_:1];
    [self sendResponse];
}

@end

@interface NewHiScoreInternalRequestHandler : NSObject <GolgiInternalInboundRequestHandler>
{
    id<TapTelegraphNewHiScoreRequestReceiver> receiver;
}

- (NewHiScoreInternalRequestHandler *)initWithReceiver:(id<TapTelegraphNewHiScoreRequestReceiver>)receiver;
@end

@implementation NewHiScoreInternalRequestHandler

- (void)incomingMsg:(NSString *)payload from:(NSString *)sender withMessageId:(NSString *)msgId
{
    TapTelegraph_newHiScore_reqArg *req = [TapTelegraph_newHiScore_reqArg deserialiseFromString:payload];

    if(req == nil){
        [Golgi sendRemoteError:@"Garbled Payload at Remote End" to:sender forMethod:@"newHiScore.TapTelegraph" withMessageId:msgId];
    }
    else{
        // Process req here
        NewHiScoreInternalResultSender *resultSender;
        resultSender = [NewHiScoreInternalResultSender alloc];
        resultSender = [resultSender initWithSender:sender andMessageId:msgId];
        [receiver newHiScoreWithResultSender:resultSender andHiScoreData:[req getHiScoreData]];
    }
}

- (NewHiScoreInternalRequestHandler *)initWithReceiver:(id<TapTelegraphNewHiScoreRequestReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;

    return self;
}
@end

@interface NewHiScoreInternalResponseHandler : NSObject <GolgiInternalInboundResponseHandler>
{
    id<TapTelegraphNewHiScoreResultReceiver> receiver;
}

- (NewHiScoreInternalResponseHandler *)initWithReceiver:(id<TapTelegraphNewHiScoreResultReceiver>)receiver;
@end
@implementation NewHiScoreInternalResponseHandler

- (void)processResponsePayload:(NSString *)payload
{
    TapTelegraph_newHiScore_rspArg *rsp = [TapTelegraph_newHiScore_rspArg deserialiseFromString:payload];

    if(rsp == nil){
        GolgiException *golgiException = [[GolgiException alloc]init];

        [golgiException setErrText:@"Corrupt Response"];
        [golgiException setErrType:GOLGI_ERRTYPE_PAYLOAD_MISMATCH];
        [receiver failureWithGolgiException:golgiException];
    }
    else if(rsp.internalSuccess_IsSet && ([rsp getInternalSuccess_] != 0)){
        [receiver success];
    }
    else if(rsp.golgiExceptionIsSet){
        [receiver failureWithGolgiException:[rsp getGolgiException]];
    }
    else{
        NSLog(@"WARNING: result for 'newHiScore' in Golgi Service 'TapTelegraph' has no expected response fields set!");
    }

}

- (void)processGolgiException:(GolgiException *)golgiException
{
	[receiver failureWithGolgiException:golgiException];
}

- (NewHiScoreInternalResponseHandler *)initWithReceiver:(id<TapTelegraphNewHiScoreResultReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;
    return self;
}

@end


@interface NewPBInternalResultSender : NSObject <TapTelegraphNewPBResultSender>
{
    NSString *sender;
    NSString *msgId;
    TapTelegraph_newPB_rspArg *rsp;
}
- (NewPBInternalResultSender *) initWithSender:(NSString *)sender andMessageId:(NSString *)msgId;
@end
@implementation NewPBInternalResultSender
- (NewPBInternalResultSender *) initWithSender:(NSString *)_sender andMessageId:(NSString *)_msgId
{
    self = [self init];
    sender = _sender;
    msgId = _msgId;
    rsp = [[TapTelegraph_newPB_rspArg alloc] initWithIsSet:NO];

    return self;
}

- (void)sendResponse
{
    [Golgi sendResponsePayload:[rsp serialise] to:sender forMethod:@"newPB.TapTelegraph" withMessageId:msgId];
}

- (void)failureWithGolgiException:(GolgiException *)golgiException
{
    [rsp setGolgiException:golgiException];
    [self sendResponse];
}

- (void)success
{
    [rsp setInternalSuccess_:1];
    [self sendResponse];
}

@end

@interface NewPBInternalRequestHandler : NSObject <GolgiInternalInboundRequestHandler>
{
    id<TapTelegraphNewPBRequestReceiver> receiver;
}

- (NewPBInternalRequestHandler *)initWithReceiver:(id<TapTelegraphNewPBRequestReceiver>)receiver;
@end

@implementation NewPBInternalRequestHandler

- (void)incomingMsg:(NSString *)payload from:(NSString *)sender withMessageId:(NSString *)msgId
{
    TapTelegraph_newPB_reqArg *req = [TapTelegraph_newPB_reqArg deserialiseFromString:payload];

    if(req == nil){
        [Golgi sendRemoteError:@"Garbled Payload at Remote End" to:sender forMethod:@"newPB.TapTelegraph" withMessageId:msgId];
    }
    else{
        // Process req here
        NewPBInternalResultSender *resultSender;
        resultSender = [NewPBInternalResultSender alloc];
        resultSender = [resultSender initWithSender:sender andMessageId:msgId];
        [receiver newPBWithResultSender:resultSender andHiScoreData:[req getHiScoreData]];
    }
}

- (NewPBInternalRequestHandler *)initWithReceiver:(id<TapTelegraphNewPBRequestReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;

    return self;
}
@end

@interface NewPBInternalResponseHandler : NSObject <GolgiInternalInboundResponseHandler>
{
    id<TapTelegraphNewPBResultReceiver> receiver;
}

- (NewPBInternalResponseHandler *)initWithReceiver:(id<TapTelegraphNewPBResultReceiver>)receiver;
@end
@implementation NewPBInternalResponseHandler

- (void)processResponsePayload:(NSString *)payload
{
    TapTelegraph_newPB_rspArg *rsp = [TapTelegraph_newPB_rspArg deserialiseFromString:payload];

    if(rsp == nil){
        GolgiException *golgiException = [[GolgiException alloc]init];

        [golgiException setErrText:@"Corrupt Response"];
        [golgiException setErrType:GOLGI_ERRTYPE_PAYLOAD_MISMATCH];
        [receiver failureWithGolgiException:golgiException];
    }
    else if(rsp.internalSuccess_IsSet && ([rsp getInternalSuccess_] != 0)){
        [receiver success];
    }
    else if(rsp.golgiExceptionIsSet){
        [receiver failureWithGolgiException:[rsp getGolgiException]];
    }
    else{
        NSLog(@"WARNING: result for 'newPB' in Golgi Service 'TapTelegraph' has no expected response fields set!");
    }

}

- (void)processGolgiException:(GolgiException *)golgiException
{
	[receiver failureWithGolgiException:golgiException];
}

- (NewPBInternalResponseHandler *)initWithReceiver:(id<TapTelegraphNewPBResultReceiver>)_receiver
{
    self = [self init];
    receiver = _receiver;
    return self;
}

@end



/********************************************************/
/********************************************************/
/********************************************************/


@implementation TapTelegraphSvc
//
// startGame
//
+ (void)sendStartGameUsingResultReceiver:(id<TapTelegraphStartGameResultReceiver>)resultReceiver andDestination:(NSString *)_dst withPlayerInfo:(PlayerInfo *)playerInfo
{
    [self sendStartGameUsingResultReceiver:resultReceiver withTransportOptions:nil andDestination:_dst withPlayerInfo:playerInfo];
}

//
// startGame with transport options
//
+ (void)sendStartGameUsingResultReceiver:(id<TapTelegraphStartGameResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPlayerInfo:(PlayerInfo *)playerInfo
{
    NSString *_payload;
    TapTelegraph_startGame_reqArg *_reqArg = [[TapTelegraph_startGame_reqArg alloc] init];
    StartGameInternalResponseHandler *_iRspHndlr;
    _iRspHndlr = [StartGameInternalResponseHandler alloc];
    _iRspHndlr = [_iRspHndlr initWithReceiver:resultReceiver];

    [_reqArg setPlayerInfo:playerInfo];
    _payload = [_reqArg serialise];

    [Golgi sendRequestPayload:_payload withTransportOptions:options to:_dst withMethod:@"startGame.TapTelegraph" andResponseHandler:_iRspHndlr];

}

+ (void)registerStartGameRequestReceiver:(id<TapTelegraphStartGameRequestReceiver>)requestReceiver
{
    StartGameInternalRequestHandler *reqHandler;
    reqHandler = [StartGameInternalRequestHandler alloc];
    reqHandler = [reqHandler initWithReceiver:requestReceiver];
    [Golgi registerRequestHandler:reqHandler forMethod:@"startGame.TapTelegraph"];
}

//
// sendTap
//
+ (void)sendSendTapUsingResultReceiver:(id<TapTelegraphSendTapResultReceiver>)resultReceiver andDestination:(NSString *)_dst withTapData:(TapData *)tapData
{
    [self sendSendTapUsingResultReceiver:resultReceiver withTransportOptions:nil andDestination:_dst withTapData:tapData];
}

//
// sendTap with transport options
//
+ (void)sendSendTapUsingResultReceiver:(id<TapTelegraphSendTapResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTapData:(TapData *)tapData
{
    NSString *_payload;
    TapTelegraph_sendTap_reqArg *_reqArg = [[TapTelegraph_sendTap_reqArg alloc] init];
    SendTapInternalResponseHandler *_iRspHndlr;
    _iRspHndlr = [SendTapInternalResponseHandler alloc];
    _iRspHndlr = [_iRspHndlr initWithReceiver:resultReceiver];

    [_reqArg setTapData:tapData];
    _payload = [_reqArg serialise];

    [Golgi sendRequestPayload:_payload withTransportOptions:options to:_dst withMethod:@"sendTap.TapTelegraph" andResponseHandler:_iRspHndlr];

}

+ (void)registerSendTapRequestReceiver:(id<TapTelegraphSendTapRequestReceiver>)requestReceiver
{
    SendTapInternalRequestHandler *reqHandler;
    reqHandler = [SendTapInternalRequestHandler alloc];
    reqHandler = [reqHandler initWithReceiver:requestReceiver];
    [Golgi registerRequestHandler:reqHandler forMethod:@"sendTap.TapTelegraph"];
}

//
// gameOver
//
+ (void)sendGameOverUsingResultReceiver:(id<TapTelegraphGameOverResultReceiver>)resultReceiver andDestination:(NSString *)_dst withGameOverData:(GameOverData *)gameOverData
{
    [self sendGameOverUsingResultReceiver:resultReceiver withTransportOptions:nil andDestination:_dst withGameOverData:gameOverData];
}

//
// gameOver with transport options
//
+ (void)sendGameOverUsingResultReceiver:(id<TapTelegraphGameOverResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withGameOverData:(GameOverData *)gameOverData
{
    NSString *_payload;
    TapTelegraph_gameOver_reqArg *_reqArg = [[TapTelegraph_gameOver_reqArg alloc] init];
    GameOverInternalResponseHandler *_iRspHndlr;
    _iRspHndlr = [GameOverInternalResponseHandler alloc];
    _iRspHndlr = [_iRspHndlr initWithReceiver:resultReceiver];

    [_reqArg setGameOverData:gameOverData];
    _payload = [_reqArg serialise];

    [Golgi sendRequestPayload:_payload withTransportOptions:options to:_dst withMethod:@"gameOver.TapTelegraph" andResponseHandler:_iRspHndlr];

}

+ (void)registerGameOverRequestReceiver:(id<TapTelegraphGameOverRequestReceiver>)requestReceiver
{
    GameOverInternalRequestHandler *reqHandler;
    reqHandler = [GameOverInternalRequestHandler alloc];
    reqHandler = [reqHandler initWithReceiver:requestReceiver];
    [Golgi registerRequestHandler:reqHandler forMethod:@"gameOver.TapTelegraph"];
}

//
// streamGame
//
+ (void)sendStreamGameUsingResultReceiver:(id<TapTelegraphStreamGameResultReceiver>)resultReceiver andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId
{
    [self sendStreamGameUsingResultReceiver:resultReceiver withTransportOptions:nil andDestination:_dst withGolgiId:golgiId];
}

//
// streamGame with transport options
//
+ (void)sendStreamGameUsingResultReceiver:(id<TapTelegraphStreamGameResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId
{
    NSString *_payload;
    TapTelegraph_streamGame_reqArg *_reqArg = [[TapTelegraph_streamGame_reqArg alloc] init];
    StreamGameInternalResponseHandler *_iRspHndlr;
    _iRspHndlr = [StreamGameInternalResponseHandler alloc];
    _iRspHndlr = [_iRspHndlr initWithReceiver:resultReceiver];

    [_reqArg setGolgiId:golgiId];
    _payload = [_reqArg serialise];

    [Golgi sendRequestPayload:_payload withTransportOptions:options to:_dst withMethod:@"streamGame.TapTelegraph" andResponseHandler:_iRspHndlr];

}

+ (void)registerStreamGameRequestReceiver:(id<TapTelegraphStreamGameRequestReceiver>)requestReceiver
{
    StreamGameInternalRequestHandler *reqHandler;
    reqHandler = [StreamGameInternalRequestHandler alloc];
    reqHandler = [reqHandler initWithReceiver:requestReceiver];
    [Golgi registerRequestHandler:reqHandler forMethod:@"streamGame.TapTelegraph"];
}

//
// getHiScore
//
+ (void)sendGetHiScoreUsingResultReceiver:(id<TapTelegraphGetHiScoreResultReceiver>)resultReceiver andDestination:(NSString *)_dst withPooky:(NSInteger)pooky
{
    [self sendGetHiScoreUsingResultReceiver:resultReceiver withTransportOptions:nil andDestination:_dst withPooky:pooky];
}

//
// getHiScore with transport options
//
+ (void)sendGetHiScoreUsingResultReceiver:(id<TapTelegraphGetHiScoreResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPooky:(NSInteger)pooky
{
    NSString *_payload;
    TapTelegraph_getHiScore_reqArg *_reqArg = [[TapTelegraph_getHiScore_reqArg alloc] init];
    GetHiScoreInternalResponseHandler *_iRspHndlr;
    _iRspHndlr = [GetHiScoreInternalResponseHandler alloc];
    _iRspHndlr = [_iRspHndlr initWithReceiver:resultReceiver];

    [_reqArg setPooky:pooky];
    _payload = [_reqArg serialise];

    [Golgi sendRequestPayload:_payload withTransportOptions:options to:_dst withMethod:@"getHiScore.TapTelegraph" andResponseHandler:_iRspHndlr];

}

+ (void)registerGetHiScoreRequestReceiver:(id<TapTelegraphGetHiScoreRequestReceiver>)requestReceiver
{
    GetHiScoreInternalRequestHandler *reqHandler;
    reqHandler = [GetHiScoreInternalRequestHandler alloc];
    reqHandler = [reqHandler initWithReceiver:requestReceiver];
    [Golgi registerRequestHandler:reqHandler forMethod:@"getHiScore.TapTelegraph"];
}

//
// newHiScore
//
+ (void)sendNewHiScoreUsingResultReceiver:(id<TapTelegraphNewHiScoreResultReceiver>)resultReceiver andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData
{
    [self sendNewHiScoreUsingResultReceiver:resultReceiver withTransportOptions:nil andDestination:_dst withHiScoreData:hiScoreData];
}

//
// newHiScore with transport options
//
+ (void)sendNewHiScoreUsingResultReceiver:(id<TapTelegraphNewHiScoreResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData
{
    NSString *_payload;
    TapTelegraph_newHiScore_reqArg *_reqArg = [[TapTelegraph_newHiScore_reqArg alloc] init];
    NewHiScoreInternalResponseHandler *_iRspHndlr;
    _iRspHndlr = [NewHiScoreInternalResponseHandler alloc];
    _iRspHndlr = [_iRspHndlr initWithReceiver:resultReceiver];

    [_reqArg setHiScoreData:hiScoreData];
    _payload = [_reqArg serialise];

    [Golgi sendRequestPayload:_payload withTransportOptions:options to:_dst withMethod:@"newHiScore.TapTelegraph" andResponseHandler:_iRspHndlr];

}

+ (void)registerNewHiScoreRequestReceiver:(id<TapTelegraphNewHiScoreRequestReceiver>)requestReceiver
{
    NewHiScoreInternalRequestHandler *reqHandler;
    reqHandler = [NewHiScoreInternalRequestHandler alloc];
    reqHandler = [reqHandler initWithReceiver:requestReceiver];
    [Golgi registerRequestHandler:reqHandler forMethod:@"newHiScore.TapTelegraph"];
}

//
// newPB
//
+ (void)sendNewPBUsingResultReceiver:(id<TapTelegraphNewPBResultReceiver>)resultReceiver andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData
{
    [self sendNewPBUsingResultReceiver:resultReceiver withTransportOptions:nil andDestination:_dst withHiScoreData:hiScoreData];
}

//
// newPB with transport options
//
+ (void)sendNewPBUsingResultReceiver:(id<TapTelegraphNewPBResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData
{
    NSString *_payload;
    TapTelegraph_newPB_reqArg *_reqArg = [[TapTelegraph_newPB_reqArg alloc] init];
    NewPBInternalResponseHandler *_iRspHndlr;
    _iRspHndlr = [NewPBInternalResponseHandler alloc];
    _iRspHndlr = [_iRspHndlr initWithReceiver:resultReceiver];

    [_reqArg setHiScoreData:hiScoreData];
    _payload = [_reqArg serialise];

    [Golgi sendRequestPayload:_payload withTransportOptions:options to:_dst withMethod:@"newPB.TapTelegraph" andResponseHandler:_iRspHndlr];

}

+ (void)registerNewPBRequestReceiver:(id<TapTelegraphNewPBRequestReceiver>)requestReceiver
{
    NewPBInternalRequestHandler *reqHandler;
    reqHandler = [NewPBInternalRequestHandler alloc];
    reqHandler = [reqHandler initWithReceiver:requestReceiver];
    [Golgi registerRequestHandler:reqHandler forMethod:@"newPB.TapTelegraph"];
}

@end
