/* IS_AUTOGENERATED_SO_ALLOW_AUTODELETE=YES */
/* The previous line is to allow auto deletion */

#import <Foundation/Foundation.h>
#import <Foundation/NSString.h>
#import "libGolgi.h"


@interface PlayerInfo : NSObject
{
    NSString *golgiId;
    BOOL golgiIdIsSet;
    NSString *name;
    BOOL nameIsSet;
    NSInteger hiScore;
    BOOL hiScoreIsSet;
    NSString *gameId;
    BOOL gameIdIsSet;
    NSInteger gameSeed;
    BOOL gameSeedIsSet;
    NSInteger appVer;
    BOOL appVerIsSet;
    NSString *os;
    BOOL osIsSet;
}

@property (readonly) BOOL golgiIdIsSet;
- (NSString *)getGolgiId;
- (void)setGolgiId:(NSString *)golgiId;
@property (readonly) BOOL nameIsSet;
- (NSString *)getName;
- (void)setName:(NSString *)name;
@property (readonly) BOOL hiScoreIsSet;
- (NSInteger)getHiScore;
- (void)setHiScore:(NSInteger )hiScore;
@property (readonly) BOOL gameIdIsSet;
- (NSString *)getGameId;
- (void)setGameId:(NSString *)gameId;
@property (readonly) BOOL gameSeedIsSet;
- (NSInteger)getGameSeed;
- (void)setGameSeed:(NSInteger )gameSeed;
@property (readonly) BOOL appVerIsSet;
- (NSInteger)getAppVer;
- (void)setAppVer:(NSInteger )appVer;
@property (readonly) BOOL osIsSet;
- (NSString *)getOs;
- (void)setOs:(NSString *)os;

+ (PlayerInfo *)deserialiseFromString: (NSString *)string;
+ (PlayerInfo *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (PlayerInfo *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (PlayerInfo *)fromJSONString:(NSString *)jsonString;
+ (PlayerInfo *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (PlayerInfo *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapData : NSObject
{
    NSString *gameId;
    BOOL gameIdIsSet;
    NSInteger screenOffset;
    BOOL screenOffsetIsSet;
    NSInteger playerY;
    BOOL playerYIsSet;
    NSInteger deltaY;
    BOOL deltaYIsSet;
    NSInteger index;
    BOOL indexIsSet;
    NSInteger score;
    BOOL scoreIsSet;
}

@property (readonly) BOOL gameIdIsSet;
- (NSString *)getGameId;
- (void)setGameId:(NSString *)gameId;
@property (readonly) BOOL screenOffsetIsSet;
- (NSInteger)getScreenOffset;
- (void)setScreenOffset:(NSInteger )screenOffset;
@property (readonly) BOOL playerYIsSet;
- (NSInteger)getPlayerY;
- (void)setPlayerY:(NSInteger )playerY;
@property (readonly) BOOL deltaYIsSet;
- (NSInteger)getDeltaY;
- (void)setDeltaY:(NSInteger )deltaY;
@property (readonly) BOOL indexIsSet;
- (NSInteger)getIndex;
- (void)setIndex:(NSInteger )index;
@property (readonly) BOOL scoreIsSet;
- (NSInteger)getScore;
- (void)setScore:(NSInteger )score;

+ (TapData *)deserialiseFromString: (NSString *)string;
+ (TapData *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapData *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapData *)fromJSONString:(NSString *)jsonString;
+ (TapData *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapData *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GameOverData : NSObject
{
    NSString *gameId;
    BOOL gameIdIsSet;
    NSInteger screenOffset;
    BOOL screenOffsetIsSet;
    NSInteger playerY;
    BOOL playerYIsSet;
    NSInteger score;
    BOOL scoreIsSet;
}

@property (readonly) BOOL gameIdIsSet;
- (NSString *)getGameId;
- (void)setGameId:(NSString *)gameId;
@property (readonly) BOOL screenOffsetIsSet;
- (NSInteger)getScreenOffset;
- (void)setScreenOffset:(NSInteger )screenOffset;
@property (readonly) BOOL playerYIsSet;
- (NSInteger)getPlayerY;
- (void)setPlayerY:(NSInteger )playerY;
@property (readonly) BOOL scoreIsSet;
- (NSInteger)getScore;
- (void)setScore:(NSInteger )score;

+ (GameOverData *)deserialiseFromString: (NSString *)string;
+ (GameOverData *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GameOverData *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GameOverData *)fromJSONString:(NSString *)jsonString;
+ (GameOverData *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GameOverData *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface HiScoreData : NSObject
{
    NSString *name;
    BOOL nameIsSet;
    NSInteger score;
    BOOL scoreIsSet;
}

@property (readonly) BOOL nameIsSet;
- (NSString *)getName;
- (void)setName:(NSString *)name;
@property (readonly) BOOL scoreIsSet;
- (NSInteger)getScore;
- (void)setScore:(NSInteger )score;

+ (HiScoreData *)deserialiseFromString: (NSString *)string;
+ (HiScoreData *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (HiScoreData *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (HiScoreData *)fromJSONString:(NSString *)jsonString;
+ (HiScoreData *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (HiScoreData *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_startGame_reqArg : NSObject
{
    PlayerInfo *playerInfo;
    BOOL playerInfoIsSet;
}

@property (readonly) BOOL playerInfoIsSet;
- (PlayerInfo *)getPlayerInfo;
- (void)setPlayerInfo:(PlayerInfo *)playerInfo;

+ (TapTelegraph_startGame_reqArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_startGame_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_startGame_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_startGame_reqArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_startGame_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_startGame_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_startGame_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (TapTelegraph_startGame_rspArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_startGame_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_startGame_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_startGame_rspArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_startGame_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_startGame_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_sendTap_reqArg : NSObject
{
    TapData *tapData;
    BOOL tapDataIsSet;
}

@property (readonly) BOOL tapDataIsSet;
- (TapData *)getTapData;
- (void)setTapData:(TapData *)tapData;

+ (TapTelegraph_sendTap_reqArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_sendTap_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_sendTap_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_sendTap_reqArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_sendTap_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_sendTap_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_sendTap_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (TapTelegraph_sendTap_rspArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_sendTap_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_sendTap_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_sendTap_rspArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_sendTap_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_sendTap_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_gameOver_reqArg : NSObject
{
    GameOverData *gameOverData;
    BOOL gameOverDataIsSet;
}

@property (readonly) BOOL gameOverDataIsSet;
- (GameOverData *)getGameOverData;
- (void)setGameOverData:(GameOverData *)gameOverData;

+ (TapTelegraph_gameOver_reqArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_gameOver_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_gameOver_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_gameOver_reqArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_gameOver_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_gameOver_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_gameOver_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (TapTelegraph_gameOver_rspArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_gameOver_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_gameOver_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_gameOver_rspArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_gameOver_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_gameOver_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_streamGame_reqArg : NSObject
{
    NSString *golgiId;
    BOOL golgiIdIsSet;
}

@property (readonly) BOOL golgiIdIsSet;
- (NSString *)getGolgiId;
- (void)setGolgiId:(NSString *)golgiId;

+ (TapTelegraph_streamGame_reqArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_streamGame_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_streamGame_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_streamGame_reqArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_streamGame_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_streamGame_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_streamGame_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (TapTelegraph_streamGame_rspArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_streamGame_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_streamGame_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_streamGame_rspArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_streamGame_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_streamGame_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_getHiScore_reqArg : NSObject
{
    NSInteger pooky;
    BOOL pookyIsSet;
}

@property (readonly) BOOL pookyIsSet;
- (NSInteger)getPooky;
- (void)setPooky:(NSInteger )pooky;

+ (TapTelegraph_getHiScore_reqArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_getHiScore_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_getHiScore_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_getHiScore_reqArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_getHiScore_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_getHiScore_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_getHiScore_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    HiScoreData *result;
    BOOL resultIsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL resultIsSet;
- (HiScoreData *)getResult;
- (void)setResult:(HiScoreData *)result;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (TapTelegraph_getHiScore_rspArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_getHiScore_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_getHiScore_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_getHiScore_rspArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_getHiScore_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_getHiScore_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_newHiScore_reqArg : NSObject
{
    HiScoreData *hiScoreData;
    BOOL hiScoreDataIsSet;
}

@property (readonly) BOOL hiScoreDataIsSet;
- (HiScoreData *)getHiScoreData;
- (void)setHiScoreData:(HiScoreData *)hiScoreData;

+ (TapTelegraph_newHiScore_reqArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_newHiScore_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_newHiScore_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_newHiScore_reqArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_newHiScore_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_newHiScore_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_newHiScore_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (TapTelegraph_newHiScore_rspArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_newHiScore_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_newHiScore_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_newHiScore_rspArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_newHiScore_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_newHiScore_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_newPB_reqArg : NSObject
{
    HiScoreData *hiScoreData;
    BOOL hiScoreDataIsSet;
}

@property (readonly) BOOL hiScoreDataIsSet;
- (HiScoreData *)getHiScoreData;
- (void)setHiScoreData:(HiScoreData *)hiScoreData;

+ (TapTelegraph_newPB_reqArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_newPB_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_newPB_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_newPB_reqArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_newPB_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_newPB_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface TapTelegraph_newPB_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (TapTelegraph_newPB_rspArg *)deserialiseFromString: (NSString *)string;
+ (TapTelegraph_newPB_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (TapTelegraph_newPB_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (TapTelegraph_newPB_rspArg *)fromJSONString:(NSString *)jsonString;
+ (TapTelegraph_newPB_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (TapTelegraph_newPB_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end
//
// startGame
//
@protocol TapTelegraphStartGameResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol TapTelegraphStartGameResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol TapTelegraphStartGameRequestReceiver
- (void)startGameWithResultSender:(id<TapTelegraphStartGameResultSender>)resultSender andPlayerInfo:(PlayerInfo *)playerInfo;
@end
@interface TapTelegraphStartGameExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// sendTap
//
@protocol TapTelegraphSendTapResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol TapTelegraphSendTapResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol TapTelegraphSendTapRequestReceiver
- (void)sendTapWithResultSender:(id<TapTelegraphSendTapResultSender>)resultSender andTapData:(TapData *)tapData;
@end
@interface TapTelegraphSendTapExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// gameOver
//
@protocol TapTelegraphGameOverResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol TapTelegraphGameOverResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol TapTelegraphGameOverRequestReceiver
- (void)gameOverWithResultSender:(id<TapTelegraphGameOverResultSender>)resultSender andGameOverData:(GameOverData *)gameOverData;
@end
@interface TapTelegraphGameOverExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// streamGame
//
@protocol TapTelegraphStreamGameResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol TapTelegraphStreamGameResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol TapTelegraphStreamGameRequestReceiver
- (void)streamGameWithResultSender:(id<TapTelegraphStreamGameResultSender>)resultSender andGolgiId:(NSString *)golgiId;
@end
@interface TapTelegraphStreamGameExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// getHiScore
//
@protocol TapTelegraphGetHiScoreResultSender
- (NSString *)getRequestSenderId;
- (void)successWithResult:(HiScoreData *)result;
@end
@protocol TapTelegraphGetHiScoreResultReceiver
- (void)successWithResult:(HiScoreData *)result;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol TapTelegraphGetHiScoreRequestReceiver
- (void)getHiScoreWithResultSender:(id<TapTelegraphGetHiScoreResultSender>)resultSender andPooky:(NSInteger)pooky;
@end
@interface TapTelegraphGetHiScoreExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// newHiScore
//
@protocol TapTelegraphNewHiScoreResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol TapTelegraphNewHiScoreResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol TapTelegraphNewHiScoreRequestReceiver
- (void)newHiScoreWithResultSender:(id<TapTelegraphNewHiScoreResultSender>)resultSender andHiScoreData:(HiScoreData *)hiScoreData;
@end
@interface TapTelegraphNewHiScoreExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// newPB
//
@protocol TapTelegraphNewPBResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol TapTelegraphNewPBResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol TapTelegraphNewPBRequestReceiver
- (void)newPBWithResultSender:(id<TapTelegraphNewPBResultSender>)resultSender andHiScoreData:(HiScoreData *)hiScoreData;
@end
@interface TapTelegraphNewPBExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

@interface TapTelegraphSvc : NSObject
+ (void)sendStartGameUsingResultReceiver:(id<TapTelegraphStartGameResultReceiver>)resultReceiver andDestination:(NSString *)_dst withPlayerInfo:(PlayerInfo *)playerInfo;
+ (void)sendStartGameUsingResultReceiver:(id<TapTelegraphStartGameResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPlayerInfo:(PlayerInfo *)playerInfo;
+ (void)sendStartGameUsingResultHandler:(void (^)(TapTelegraphStartGameExceptionBundle *))resultHandler andDestination:(NSString *)_dst withPlayerInfo:(PlayerInfo *)playerInfo;
+ (void)sendStartGameUsingResultHandler:(void (^)(TapTelegraphStartGameExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPlayerInfo:(PlayerInfo *)playerInfo;
+ (void)httpSendStartGameUsingResultHandler:(void (^)(TapTelegraphStartGameExceptionBundle *))resultHandler andDestination:(NSString *)_dst withPlayerInfo:(PlayerInfo *)playerInfo;
+ (void)sendStartGameUsingResultReceiver:(id<TapTelegraphStartGameResultReceiver>)resultReceiver orResultHandler:(void (^)(TapTelegraphStartGameExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPlayerInfo:(PlayerInfo *)playerInfo;
+ (void)registerStartGameRequestReceiver:(id<TapTelegraphStartGameRequestReceiver>)requestReceiver;
+ (void)registerStartGameRequestHandler:(void (^)(id<TapTelegraphStartGameResultSender> resultSender, PlayerInfo * playerInfo))requestHandler;

+ (void)sendSendTapUsingResultReceiver:(id<TapTelegraphSendTapResultReceiver>)resultReceiver andDestination:(NSString *)_dst withTapData:(TapData *)tapData;
+ (void)sendSendTapUsingResultReceiver:(id<TapTelegraphSendTapResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTapData:(TapData *)tapData;
+ (void)sendSendTapUsingResultHandler:(void (^)(TapTelegraphSendTapExceptionBundle *))resultHandler andDestination:(NSString *)_dst withTapData:(TapData *)tapData;
+ (void)sendSendTapUsingResultHandler:(void (^)(TapTelegraphSendTapExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTapData:(TapData *)tapData;
+ (void)httpSendSendTapUsingResultHandler:(void (^)(TapTelegraphSendTapExceptionBundle *))resultHandler andDestination:(NSString *)_dst withTapData:(TapData *)tapData;
+ (void)sendSendTapUsingResultReceiver:(id<TapTelegraphSendTapResultReceiver>)resultReceiver orResultHandler:(void (^)(TapTelegraphSendTapExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTapData:(TapData *)tapData;
+ (void)registerSendTapRequestReceiver:(id<TapTelegraphSendTapRequestReceiver>)requestReceiver;
+ (void)registerSendTapRequestHandler:(void (^)(id<TapTelegraphSendTapResultSender> resultSender, TapData * tapData))requestHandler;

+ (void)sendGameOverUsingResultReceiver:(id<TapTelegraphGameOverResultReceiver>)resultReceiver andDestination:(NSString *)_dst withGameOverData:(GameOverData *)gameOverData;
+ (void)sendGameOverUsingResultReceiver:(id<TapTelegraphGameOverResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withGameOverData:(GameOverData *)gameOverData;
+ (void)sendGameOverUsingResultHandler:(void (^)(TapTelegraphGameOverExceptionBundle *))resultHandler andDestination:(NSString *)_dst withGameOverData:(GameOverData *)gameOverData;
+ (void)sendGameOverUsingResultHandler:(void (^)(TapTelegraphGameOverExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withGameOverData:(GameOverData *)gameOverData;
+ (void)httpSendGameOverUsingResultHandler:(void (^)(TapTelegraphGameOverExceptionBundle *))resultHandler andDestination:(NSString *)_dst withGameOverData:(GameOverData *)gameOverData;
+ (void)sendGameOverUsingResultReceiver:(id<TapTelegraphGameOverResultReceiver>)resultReceiver orResultHandler:(void (^)(TapTelegraphGameOverExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withGameOverData:(GameOverData *)gameOverData;
+ (void)registerGameOverRequestReceiver:(id<TapTelegraphGameOverRequestReceiver>)requestReceiver;
+ (void)registerGameOverRequestHandler:(void (^)(id<TapTelegraphGameOverResultSender> resultSender, GameOverData * gameOverData))requestHandler;

+ (void)sendStreamGameUsingResultReceiver:(id<TapTelegraphStreamGameResultReceiver>)resultReceiver andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId;
+ (void)sendStreamGameUsingResultReceiver:(id<TapTelegraphStreamGameResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId;
+ (void)sendStreamGameUsingResultHandler:(void (^)(TapTelegraphStreamGameExceptionBundle *))resultHandler andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId;
+ (void)sendStreamGameUsingResultHandler:(void (^)(TapTelegraphStreamGameExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId;
+ (void)httpSendStreamGameUsingResultHandler:(void (^)(TapTelegraphStreamGameExceptionBundle *))resultHandler andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId;
+ (void)sendStreamGameUsingResultReceiver:(id<TapTelegraphStreamGameResultReceiver>)resultReceiver orResultHandler:(void (^)(TapTelegraphStreamGameExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId;
+ (void)registerStreamGameRequestReceiver:(id<TapTelegraphStreamGameRequestReceiver>)requestReceiver;
+ (void)registerStreamGameRequestHandler:(void (^)(id<TapTelegraphStreamGameResultSender> resultSender, NSString * golgiId))requestHandler;

+ (void)sendGetHiScoreUsingResultReceiver:(id<TapTelegraphGetHiScoreResultReceiver>)resultReceiver andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)sendGetHiScoreUsingResultReceiver:(id<TapTelegraphGetHiScoreResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)sendGetHiScoreUsingResultHandler:(void (^)(HiScoreData *, TapTelegraphGetHiScoreExceptionBundle *))resultHandler andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)sendGetHiScoreUsingResultHandler:(void (^)(HiScoreData *, TapTelegraphGetHiScoreExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)httpSendGetHiScoreUsingResultHandler:(void (^)(HiScoreData *, TapTelegraphGetHiScoreExceptionBundle *))resultHandler andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)sendGetHiScoreUsingResultReceiver:(id<TapTelegraphGetHiScoreResultReceiver>)resultReceiver orResultHandler:(void (^)(HiScoreData *, TapTelegraphGetHiScoreExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)registerGetHiScoreRequestReceiver:(id<TapTelegraphGetHiScoreRequestReceiver>)requestReceiver;
+ (void)registerGetHiScoreRequestHandler:(void (^)(id<TapTelegraphGetHiScoreResultSender> resultSender, NSInteger pooky))requestHandler;

+ (void)sendNewHiScoreUsingResultReceiver:(id<TapTelegraphNewHiScoreResultReceiver>)resultReceiver andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)sendNewHiScoreUsingResultReceiver:(id<TapTelegraphNewHiScoreResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)sendNewHiScoreUsingResultHandler:(void (^)(TapTelegraphNewHiScoreExceptionBundle *))resultHandler andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)sendNewHiScoreUsingResultHandler:(void (^)(TapTelegraphNewHiScoreExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)httpSendNewHiScoreUsingResultHandler:(void (^)(TapTelegraphNewHiScoreExceptionBundle *))resultHandler andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)sendNewHiScoreUsingResultReceiver:(id<TapTelegraphNewHiScoreResultReceiver>)resultReceiver orResultHandler:(void (^)(TapTelegraphNewHiScoreExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)registerNewHiScoreRequestReceiver:(id<TapTelegraphNewHiScoreRequestReceiver>)requestReceiver;
+ (void)registerNewHiScoreRequestHandler:(void (^)(id<TapTelegraphNewHiScoreResultSender> resultSender, HiScoreData * hiScoreData))requestHandler;

+ (void)sendNewPBUsingResultReceiver:(id<TapTelegraphNewPBResultReceiver>)resultReceiver andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)sendNewPBUsingResultReceiver:(id<TapTelegraphNewPBResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)sendNewPBUsingResultHandler:(void (^)(TapTelegraphNewPBExceptionBundle *))resultHandler andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)sendNewPBUsingResultHandler:(void (^)(TapTelegraphNewPBExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)httpSendNewPBUsingResultHandler:(void (^)(TapTelegraphNewPBExceptionBundle *))resultHandler andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)sendNewPBUsingResultReceiver:(id<TapTelegraphNewPBResultReceiver>)resultReceiver orResultHandler:(void (^)(TapTelegraphNewPBExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withHiScoreData:(HiScoreData *)hiScoreData;
+ (void)registerNewPBRequestReceiver:(id<TapTelegraphNewPBRequestReceiver>)requestReceiver;
+ (void)registerNewPBRequestHandler:(void (^)(id<TapTelegraphNewPBResultSender> resultSender, HiScoreData * hiScoreData))requestHandler;

@end
